apiVersion: v1
kind: Service
metadata:
  name: communication-control
spec:
  selector:
    app: communication-control
  ports:
    - protocol: TCP
      port: 8080      
      targetPort: 8080  
  type: ClusterIP      