apiVersion: v1
kind: Service
metadata:
  name: map-client
spec:
  type: NodePort
  selector:
    app: map-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   
      nodePort: 30080  