name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  IMAGE_REGISTRY: registry.digitalocean.com/lab5registry
  NAMESPACE: lab6

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Log in to DigitalOcean Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USER }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Build and push CommunicationControl
        run: |
          docker build -t $IMAGE_REGISTRY/communication-control:latest -f src/CommunicationControl/DevOpsProject/Dockerfile .
          docker push $IMAGE_REGISTRY/communication-control:latest

      - name: Build and push HiveMind
        run: |
          docker build -t $IMAGE_REGISTRY/hivemind:latest -f src/CommunicationControl/DevOpsProject.HiveMind.API/Dockerfile .
          docker push $IMAGE_REGISTRY/hivemind:latest

      - name: Build and push MapClient
        run: |
          docker build -t $IMAGE_REGISTRY/map-client:latest -f src/MapClient/Dockerfile src/MapClient
          docker push $IMAGE_REGISTRY/map-client:latest

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up GKE credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: autopilot-cluster-lab6-cluster1
          location: europe-west1
          project_id: absolute-cubist-461719-f9

      - name: Deploy manifests to GKE
        run: |
          kubectl apply -f manifest/ -n $NAMESPACE
          kubectl rollout restart deployment communication-control -n $NAMESPACE
          kubectl rollout restart deployment hivemind -n $NAMESPACE
          kubectl rollout restart deployment map-client -n $NAMESPACE